export const SUPABASE_URL = 'https://bzygansrlmyodltbmymm.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eWdhbnNybG15b2RsdGJteW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDgzMzIwMDUsImV4cCI6MjAyMzkwODAwNX0.pJce4_yHr7TaHTUj9fnrGSwcWWcKlXRHRWRkP1Oe3c4';
